import LegalPage from '../components/LegalPage';

const sections = [
  { title: '1. About the Website', paragraphs: ['This website is operated by Raja Organic Farms and is intended to provide information about our farming activities, agricultural products, cultivation practices, sustainability initiatives and related business activities.', 'The information provided on this website is intended for general informational purposes and may be updated or changed from time to time.'] },
  { title: '2. Acceptance of Terms', paragraphs: ['By accessing, browsing or using this website, you confirm that you have read, understood and agreed to these Terms and Conditions.', 'These terms apply to all visitors, users and individuals who access or interact with the website.'] },
  { title: '3. Website Content', paragraphs: ['We make reasonable efforts to ensure that the information presented on this website is accurate and up to date.', 'However, agricultural practices, product availability, cultivation cycles, seasonal conditions and other business information may change from time to time.', 'Raja Organic Farms does not guarantee that all information on the website will always be complete, current, accurate or free from errors.', 'We reserve the right to modify, update, add or remove website content at any time without prior notice.'] },
  { title: '4. Product Information and Availability', paragraphs: ['Information relating to agricultural products displayed on the website is provided for general reference.', 'Product availability, varieties, quantities, quality, harvest periods and other characteristics may vary depending on seasonal and agricultural conditions.', 'The appearance of a product on the website does not necessarily mean that the product is currently available for purchase.', 'For current availability, pricing, bulk requirements or specific product enquiries, please contact Raja Organic Farms directly.'] },
  { title: '5. Product Quality', paragraphs: ['Raja Organic Farms takes reasonable care in cultivating and handling its agricultural produce.', 'However, natural agricultural products may vary in size, colour, appearance, texture, taste and other characteristics depending on factors such as variety, season, soil, climate and harvest conditions.', 'Such natural variations should not automatically be considered defects.'] },
  { title: '6. Organic and Sustainability Claims', paragraphs: ['Where the website refers to organic, natural, sustainable or responsible farming practices, such descriptions should be understood in the context of the specific farming practices and products to which they relate.', 'Any certification, accreditation or formal organic status will be stated only where applicable and supported by the relevant documentation.', 'Visitors should contact Raja Organic Farms directly if they require specific information regarding certifications, farming methods or product standards.'] },
  { title: '7. Enquiries and Communications', paragraphs: ['Visitors may submit enquiries through the contact forms or other communication channels provided on the website.', 'By submitting an enquiry, you agree to provide accurate and relevant information so that we can respond appropriately.', 'Submission of an enquiry does not create a contract, purchase agreement, partnership or other binding relationship with Raja Organic Farms unless separately agreed and confirmed by the parties.'] },
  { title: '8. Intellectual Property', paragraphs: ['Unless otherwise stated, all content appearing on this website is owned by or licensed to Raja Organic Farms.', 'This includes, but is not limited to:', 'The content may not be copied, reproduced, modified, distributed, published or commercially used without prior written permission from Raja Organic Farms.', 'You may view and use the website for personal or legitimate business information purposes, provided that you do not infringe our intellectual property rights.'], bullets: ['Website text', 'Logos and brand elements', 'Images and photographs', 'Graphics and illustrations', 'Videos', 'Design elements', 'Icons', 'Other original website content'] },
  { title: '9. User Submitted Content', paragraphs: ['If you voluntarily submit information, comments, feedback, photographs or other content through the website, you confirm that you have the right to provide such content.', 'You should not submit content that:', 'Raja Organic Farms reserves the right to remove or disregard inappropriate or unauthorised content submitted through the website.'], bullets: ['Violates applicable laws', 'Infringes the rights of another person', 'Contains malicious software', 'Contains confidential information belonging to another party', 'Is misleading, offensive or unlawful'] },
  { title: '10. Third Party Links', paragraphs: ['The website may contain links to third party websites, platforms or services for convenience or additional information.', 'These links do not necessarily represent an endorsement or recommendation by Raja Organic Farms.', 'We do not control third party websites and are not responsible for their content, availability, security, privacy practices or terms of use.', 'Users should review the terms and privacy policies applicable to any third party website they visit.'] },
  { title: '11. Website Availability', paragraphs: ['We aim to keep our website accessible and functioning properly. However, we cannot guarantee uninterrupted or error free availability.', 'The website may occasionally become unavailable due to maintenance, technical issues, security measures, updates, server problems or circumstances beyond our reasonable control.', 'We reserve the right to modify, suspend or discontinue any part of the website without prior notice.'] },
  { title: '12. Prohibited Use', paragraphs: ['You agree not to use this website for any unlawful or unauthorised purpose.', 'You must not:'], bullets: ['Attempt to gain unauthorised access to the website or its systems', 'Introduce viruses, malware or other harmful code', 'Interfere with the security or operation of the website', 'Copy or reproduce website content without permission', 'Use automated systems to collect website content without authorisation', 'Misrepresent your identity or relationship with Raja Organic Farms', 'Use the website in a manner that violates applicable laws or regulations'] },
  { title: '13. Disclaimer', paragraphs: ['The information provided on this website is made available on an "as is" and "as available" basis.', 'To the extent permitted by applicable law, Raja Organic Farms does not make warranties or representations regarding the completeness, accuracy, reliability, availability or suitability of the website or its content for any particular purpose.', 'Information relating to agricultural practices and products may naturally change due to environmental, seasonal, operational and other factors.'] },
  { title: '14. Limitation of Liability', paragraphs: ['To the extent permitted by applicable law, Raja Organic Farms shall not be responsible for any direct, indirect, incidental, consequential or other loss arising from or relating to:', 'Nothing in these Terms and Conditions shall exclude or limit liability where such exclusion or limitation is not permitted under applicable law.'], bullets: ['Use of or inability to use the website', 'Reliance on information provided on the website', 'Temporary website unavailability', 'Errors or omissions in website content', 'Third party websites or services accessed through links', 'Unauthorised access or technical events beyond our reasonable control'] },
  { title: '15. Privacy', paragraphs: ['Your use of this website is also subject to our Privacy Policy, which explains how we collect, use and protect personal information.', 'By using the website, you acknowledge that you have read and understood our Privacy Policy.'] },
  { title: '16. Changes to These Terms', paragraphs: ['Raja Organic Farms may update or modify these Terms and Conditions from time to time.', 'Changes will become effective when the revised terms are published on this website, unless otherwise stated.', 'We recommend reviewing this page periodically to remain informed about the current terms applicable to your use of the website.'] },
  { title: '17. Governing Law', paragraphs: ['These Terms and Conditions shall be governed by and interpreted in accordance with the applicable laws of India.', 'Any disputes arising in connection with the use of this website shall be subject to the jurisdiction of the appropriate courts in India.'] },
  { title: '18. Contact Us', paragraphs: ['If you have any questions regarding these Terms and Conditions, please contact us.', 'Raja Organic Farms', 'Address: [Complete Address]', 'Email: [Official Email Address]', 'Phone: [Contact Number]'] },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms and Conditions"
      intro={[
        'Welcome to the website of Raja Organic Farms. By accessing or using this website, you agree to comply with and be bound by the following Terms and Conditions.',
        'Please read these terms carefully before using our website. If you do not agree with any part of these terms, please discontinue use of the website.',
      ]}
      sections={sections}
      closingTitle="Our Commitment"
      closing={[
        'At Raja Organic Farms, we believe meaningful relationships are built on trust, transparency and responsibility.',
        'These Terms and Conditions help ensure that our website remains a reliable source of information while protecting the interests of our visitors, customers and the Raja Organic Farms brand.',
        'RAJA ORGANIC FARMS',
        'In Harmony with Nature. Growing for Tomorrow.',
      ]}
    />
  );
}
